### ISSUE TITLE
Designer problem when using the single frontend-resources fix

### ISSUE THREAD

**Issue by QNENet** [vaadin/vaadin-flow-karaf-example#54]
Using the temporary fix for designer in the flow karaf example. 

Most works well, in fact it is starting to look like a real snappy gui with the add and remove views just by adding and/or removing the view jar from the deploy folder. Functionality I have been trying to achieve for a long time.  

But if I try the v19-20 designer tutorial the form when added to the main view does not appear and it stuffs up the whole view.

This problem occurs in my project views as well.

**Comment by pleku** [comment]
We would need the steps and code to reproduce the issue to be able to do anything about this, as the report seems to take some knowledge for granted ... please provide the concrete steps on how to reproduce the issue. Pinging @mstahv @vaadin/vaadin-designer-team if they know what this is about.

**Comment by QNENet** [comment]
Similar situation to #55
I have decided to abandon the use of designer at this stage due to the complications of using it with OSGi/Karaf.
These complication make direct coding views a better proposition if/until the situation improves.
