### ISSUE TITLE
Using Vaadin Icons in Designer

### ISSUE THREAD

**Issue by QNENet** [vaadin/vaadin-flow-karaf-example#55]
Using the temporary single frontend-resources fix for designer I can only see a few lumo icons.

There have been issues raised on the forum in the past about this problem but no fix can I find.

What is the process for using other icons other than the limited lumo range in the designer attributes?

**Comment by pleku** [comment]
I'm not exactly sure what this refers to, but apparently Vaadin icons are missing from Designer ? I'm pretty sure we'll need more details, but pinging @vaadin/vaadin-designer-team just in case they know what this is about

**Comment by QNENet** [comment]
I have decided to abandon the use of designer at this stage due to the complications of using it with OSGi/Karaf.
These  complication make direct coding views a better proposition if/until the situation improves.
