### ISSUE TITLE
Suggested alternate version

### ISSUE THREAD

**Issue by jhapy** [vaadin/vaadin-flow-karaf-example#61]
Dear,

Is-it possible to have an alternate example, based on this one, but using Spring Boot and Osgi (as bundle) ?

- I've managed to run this example on Karaf
- I've managed to have a Spring Boot Application on Karaf

But not both at the same time...

In fact, when trying, no route are being registered and FixedVaadinServlet is never called.

Best regards.

Alexandre

**Comment by caalador** [comment]
spring-boot resources are not OSGi compatible so it is not possible to use boot with OSGi.
