### ISSUE TITLE
PiT v23: demo notification: Greet service not currently available

### ISSUE THREAD

**Issue by manolo** [vaadin/vaadin-flow-karaf-example#76]
When running the example and clicking on the 'say hello' button, the notification shows a message with the text: 'Greet service not currently available, install it into Karaf to get a proper greeting'  

This already happens in v22 but it was detected when doing v23 PiT.

```
git clone https://github.com/vaadin/vaadin-flow-karaf-example.git
cd vaadin-flow-karaf-example.git
mvn install
mvn -pl main-ui install -Prun
open http://localhost:8181

```

**Comment by caalador** [comment]
The project works as documented in the README.md
As the greetservice-impl is not a dependency of main-ui it will not be deployed when running `mvn -pl main-ui install -Prun` to showcase that we can only have the API available.

Going through the steps in the dynamic tutorial or adding the `greetservice-impl`as a dependency to `main-ui` will make the greetservice deploy to karaf.
